// This file is generated by scripts/sync-codex-impl-assets.ts
// Do not edit manually.

export const EMBEDDED_PROMPTS = {
  "apply-fix-batch.md": "# Fix Batch Primitive\n\nApply only the fixes listed in the provided fix batch.\n\nRules:\n- Do not expand scope.\n- Do not weaken tests.\n- Re-run the story or feature gate before you finish.\n- Return `DONE` only when the requested fixes are applied and the gate passes.\n",
  "implement-story.md": "# Story Implement Primitive\n\nImplement the current story from the provided spec pack artifacts.\n\nRules:\n- Stay inside this story's scope.\n- Follow the test plan and tech design.\n- Run the story gate before you finish.\n- If the story cannot be completed without human judgment, return `BLOCKED`.\n- If you finish the story implementation and the gate passes, return `DONE`.\n",
  "start-process.md": "# Codex Process Start\n\nYou are operating inside the Codex-first scripted process harness.\n\nThe process runner owns lifecycle, retries, gate execution, artifact harvesting,\nand story-to-story advancement.\n\nYou are a one-shot worker. Read the provided artifacts, perform only the work\nfor this primitive, and finish by returning schema-conforming JSON.\n",
  "synthesize-feature.md": "# Feature Synthesis Primitive\n\nRead the primary and secondary feature review artifacts and decide:\n- `PASS`\n- `REVISE`\n- `BLOCK`\n\nMap your decision into process status:\n- `PASS` -> `DONE`\n- `REVISE` -> `NEEDS_REWORK`\n- `BLOCK` -> `BLOCKED`\n",
  "synthesize-story.md": "# Story Synthesis Primitive\n\nRead the primary and secondary story review artifacts and decide the next story\ntransition.\n\nDecision rules:\n- `PASS` when the story can be accepted as-is\n- `REVISE` when the story needs a bounded fix batch\n- `BLOCK` when the process requires human judgment\n\nMap your decision into process status:\n- `PASS` -> `status = DONE`\n- `REVISE` -> `status = NEEDS_REWORK`\n- `BLOCK` -> `status = BLOCKED`\n",
  "verify-feature-primary.md": "# Feature Verification Primitive — Primary\n\nReview the full implemented feature across all stories.\n\nFocus on:\n- cross-story correctness\n- architecture drift\n- production-path gaps\n- real store/runtime behavior\n- full feature gate result\n\nReturn structured JSON only.\n",
  "verify-feature-secondary.md": "# Feature Verification Primitive — Secondary\n\nIndependently review the full implemented feature across all stories.\n\nFocus on:\n- requirements completeness\n- cross-story consistency\n- test quality\n- feature gate result\n\nReturn structured JSON only.\n",
  "verify-story-primary.md": "# Story Verification Primitive — Primary\n\nYou are the primary story verifier.\n\nReview the current implementation against:\n- the story\n- the epic\n- the tech design\n- the test plan\n- the verification bundle\n\nRun the story acceptance gate. Return:\n- `DONE` when no blocking issue remains\n- `NEEDS_REWORK` when a bounded fix batch is required\n- `BLOCKED` when the process cannot continue without human judgment\n",
  "verify-story-secondary.md": "# Story Verification Primitive — Secondary\n\nYou are the secondary story verifier.\n\nIndependently review the same story and verification bundle. Use fresh judgment.\nRun the same story acceptance gate. Return structured JSON only.\n"
} as const;

export const EMBEDDED_SCHEMAS = {
  "primitive-status.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "processType",
      "primitiveSlug",
      "status",
      "codexEvidenceRef",
      "reportMarkdown",
      "milestones",
      "unresolvedFindings",
      "notes",
      "requiresUserDecision",
      "nextRecommendedAction"
    ],
    "properties": {
      "processType": {
        "const": "codex-impl"
      },
      "primitiveSlug": {
        "type": "string",
        "enum": [
          "codex54-xhigh-story-implement",
          "codex54-xhigh-story-verify-primary",
          "gpt53-codex-high-story-verify-secondary",
          "codex54-xhigh-story-synthesize",
          "codex54-xhigh-story-fix-batch",
          "codex54-xhigh-feature-verify-primary",
          "gpt53-codex-high-feature-verify-secondary",
          "codex54-xhigh-feature-synthesize"
        ]
      },
      "storyId": {
        "type": "string"
      },
      "featureVerification": {
        "type": "boolean"
      },
      "status": {
        "type": "string",
        "enum": [
          "DONE",
          "NEEDS_REWORK",
          "BLOCKED"
        ]
      },
      "codexEvidenceRef": {
        "type": "string",
        "minLength": 1
      },
      "reportMarkdown": {
        "type": "string",
        "minLength": 1
      },
      "milestones": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "unresolvedFindings": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "disposition"
          ],
          "properties": {
            "id": {
              "type": "string"
            },
            "title": {
              "type": "string"
            },
            "disposition": {
              "type": "string",
              "enum": [
                "fixed",
                "accepted-risk",
                "defer"
              ]
            },
            "severity": {
              "type": "string",
              "enum": [
                "CRITICAL",
                "MAJOR",
                "MINOR",
                "INFO"
              ]
            }
          }
        }
      },
      "notes": {
        "type": "string"
      },
      "requiresUserDecision": {
        "type": "boolean"
      },
      "nextRecommendedAction": {
        "type": "string",
        "minLength": 1
      },
      "gateResultSummary": {
        "type": "string"
      }
    }
  },
  "synthesis-result.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "processType",
      "primitiveSlug",
      "status",
      "decision",
      "codexEvidenceRef",
      "reportMarkdown",
      "milestones",
      "unresolvedFindings",
      "notes",
      "requiresUserDecision",
      "nextRecommendedAction"
    ],
    "properties": {
      "processType": {
        "const": "codex-impl"
      },
      "primitiveSlug": {
        "type": "string",
        "enum": [
          "codex54-xhigh-story-synthesize",
          "codex54-xhigh-feature-synthesize"
        ]
      },
      "storyId": {
        "type": "string"
      },
      "featureVerification": {
        "type": "boolean"
      },
      "status": {
        "type": "string",
        "enum": [
          "DONE",
          "NEEDS_REWORK",
          "BLOCKED"
        ]
      },
      "decision": {
        "type": "string",
        "enum": [
          "PASS",
          "REVISE",
          "BLOCK"
        ]
      },
      "codexEvidenceRef": {
        "type": "string",
        "minLength": 1
      },
      "reportMarkdown": {
        "type": "string",
        "minLength": 1
      },
      "milestones": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "unresolvedFindings": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "disposition"
          ],
          "properties": {
            "id": {
              "type": "string"
            },
            "title": {
              "type": "string"
            },
            "disposition": {
              "type": "string",
              "enum": [
                "fixed",
                "accepted-risk",
                "defer"
              ]
            },
            "severity": {
              "type": "string",
              "enum": [
                "CRITICAL",
                "MAJOR",
                "MINOR",
                "INFO"
              ]
            }
          }
        }
      },
      "notes": {
        "type": "string"
      },
      "requiresUserDecision": {
        "type": "boolean"
      },
      "nextRecommendedAction": {
        "type": "string",
        "minLength": 1
      },
      "gateResultSummary": {
        "type": "string"
      }
    }
  }
} as const;
