// This file is generated by scripts/sync-impl-cli-assets.ts
// Do not edit manually.

export const EMBEDDED_PROMPT_ASSETS = {
  "base": {
    "epic-synthesizer.md": "# Epic Synthesizer Base Prompt\n\n## Confirmed Issues\nList only issues that remain supported by the verifier evidence.\nYou must independently verify verifier-reported issues against the codebase and epic artifacts before you confirm them.\n\n## Disputed or Unconfirmed Issues\nKeep disputed or unconfirmed issues separate from confirmed issues.\n\n## Output Contract\nReturn exactly one JSON object matching `{{RESULT_CONTRACT_NAME}}`.\n",
    "epic-verifier.md": "# Epic Verifier Base Prompt\n\n## Cross-Story Checks\nReview the implemented epic as a whole codebase rather than as isolated stories.\n\n## Architecture Consistency\nCheck for cross-story drift against the architecture and tech-design contracts.\n\n## Mock Audit\nPerform a production-path mock or shim audit and report every material finding.\n\n## Output Contract\nReturn exactly one JSON object matching `{{RESULT_CONTRACT_NAME}}`.\n",
    "quick-fixer.md": "# Quick Fixer Base Prompt\n\n{{FOLLOWUP_REQUEST}}\n",
    "story-implementor.md": "# Story Implementor Base Prompt\n\n## Role Stance\nYou are the story implementor for `{{STORY_ID}}` (`{{STORY_TITLE}}`).\nStay inside the current story scope unless the story explicitly requires adjacent edits.\n\n## Artifact Reading Order\nUse the appended reading journey before you change code.\nKeep your decisions grounded in the current story, the full tech-design set, and the test plan.\n\n## Self-Review\nIf a self-review pass is appended, treat it as part of the required workflow.\nDo not skip required fixes, open questions, or surfaced risks.\n\n## Output Contract\nReturn exactly one JSON object matching `{{RESULT_CONTRACT_NAME}}`.\n",
    "story-verifier.md": "# Story Verifier Base Prompt\n\n## Role Stance\nYou are verifier `{{VERIFIER_LABEL}}` for `{{STORY_ID}}` (`{{STORY_TITLE}}`).\nProduce evidence-backed findings rather than implementation suggestions first.\n\n## Evidence Rules\nBase every finding on code, tests, artifacts, or a clearly stated missing proof point.\n\n## Severity\nUse `critical`, `major`, `minor`, or `observation`.\n\n## AC / TC Coverage\nVerify the story against explicit AC and TC evidence before you conclude the outcome.\n\n## Output Contract\nReturn exactly one JSON object matching `{{RESULT_CONTRACT_NAME}}`.\n{{ROUTING_GUIDANCE}}\n"
  },
  "snippets": {
    "gate-instructions.md": "## Gate Instructions\n- Story Gate: {{STORY_GATE_COMMAND}}\n- Epic Gate: {{EPIC_GATE_COMMAND}}\n",
    "mock-audit.md": "## Mock Or Shim Audit\nAudit production paths for mocks, shims, or fake adapters and report every material finding explicitly.\n",
    "reading-journey.md": "## Reading Journey\n{{READING_JOURNEY}}\n",
    "report-contract.md": "## Result Contract\nReturn exactly one JSON object matching `{{RESULT_CONTRACT_NAME}}`.\n{{ROUTING_GUIDANCE}}\n",
    "self-review-pass-1.md": "## Self Review\nSelf-review pass 1: broad correctness and obvious omissions.\n",
    "self-review-pass-2.md": "## Self Review\nSelf-review pass 2: requirement alignment, test coverage, and missing evidence.\n",
    "self-review-pass-3.md": "## Self Review\nSelf-review pass 3: residual risks, scope edges, and cleanup before handoff.\n"
  }
} as const;
