import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const PROMPTS_DIR = join(ROOT, "processes", "codex-impl", "prompts");
const SCHEMAS_DIR = join(ROOT, "processes", "codex-impl", "schemas");
const OUTPUT_PATH = join(
  ROOT,
  "processes",
  "codex-impl",
  "core",
  "embedded-assets.generated.ts"
);

export async function syncCodexImplAssets(): Promise<void> {
  const [promptEntries, schemaEntries] = await Promise.all([
    loadTextDirectory(PROMPTS_DIR),
    loadJsonDirectory(SCHEMAS_DIR),
  ]);

  const output = [
    "// This file is generated by scripts/sync-codex-impl-assets.ts",
    "// Do not edit manually.",
    "",
    "export const EMBEDDED_PROMPTS = " +
      JSON.stringify(promptEntries, null, 2) +
      " as const;",
    "",
    "export const EMBEDDED_SCHEMAS = " +
      JSON.stringify(schemaEntries, null, 2) +
      " as const;",
    "",
  ].join("\n");

  await writeFile(OUTPUT_PATH, output, "utf8");
}

async function loadTextDirectory(dir: string): Promise<Record<string, string>> {
  const entries = await readdir(dir, { withFileTypes: true });
  const result: Record<string, string> = {};

  for (const entry of entries) {
    if (!entry.isFile()) {
      continue;
    }
    const path = join(dir, entry.name);
    result[entry.name] = await readFile(path, "utf8");
  }

  return sortRecord(result);
}

async function loadJsonDirectory(dir: string): Promise<Record<string, unknown>> {
  const entries = await readdir(dir, { withFileTypes: true });
  const result: Record<string, unknown> = {};

  for (const entry of entries) {
    if (!entry.isFile()) {
      continue;
    }
    const path = join(dir, entry.name);
    result[entry.name] = JSON.parse(await readFile(path, "utf8"));
  }

  return sortRecord(result);
}

function sortRecord<T>(value: Record<string, T>): Record<string, T> {
  return Object.fromEntries(
    Object.entries(value).sort(([left], [right]) => left.localeCompare(right))
  );
}

if (import.meta.path === Bun.main) {
  await syncCodexImplAssets();
}
