import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const PROMPTS_DIR = join(ROOT, "processes", "impl-cli", "prompts");
const OUTPUT_PATH = join(
  ROOT,
  "processes",
  "impl-cli",
  "core",
  "embedded-assets.generated.ts"
);

async function loadTextDirectory(dir: string): Promise<Record<string, string>> {
  const entries = await readdir(dir, { withFileTypes: true });
  const result: Record<string, string> = {};

  for (const entry of entries) {
    if (!entry.isFile()) {
      continue;
    }
    result[entry.name] = await readFile(join(dir, entry.name), "utf8");
  }

  return Object.fromEntries(
    Object.entries(result).sort(([left], [right]) => left.localeCompare(right))
  );
}

export async function syncImplCliAssets(): Promise<void> {
  const [base, snippets] = await Promise.all([
    loadTextDirectory(join(PROMPTS_DIR, "base")),
    loadTextDirectory(join(PROMPTS_DIR, "snippets")),
  ]);

  const output = [
    "// This file is generated by scripts/sync-impl-cli-assets.ts",
    "// Do not edit manually.",
    "",
    "export const EMBEDDED_PROMPT_ASSETS = " +
      JSON.stringify(
        {
          base,
          snippets,
        },
        null,
        2
      ) +
      " as const;",
    "",
  ].join("\n");

  await writeFile(OUTPUT_PATH, output, "utf8");
}

if (import.meta.path === Bun.main) {
  await syncImplCliAssets();
}
